# Site settings
title: Jorge A. Torres
email: j@jorgetorres.co
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jorgetorres.co" # the base hostname & protocol for your site
twitter_username: jorgealtrapo
github_username:  jorgeatorres

# Build settings
timezone: America/Bogota
markdown: kramdown
